description: >-
  Training BERT-base wih $TRAIN_DATASET
tasks:
  - spec:
      image: MultiQA_with_hyper-param-search-v11
      resultPath: /output
      args:
        - python
        - -u
        - run_experiments.py
        - $TRAIN_DATASET
        - SQuAD1-1,NewsQA,SearchQA,TriviaQA_wiki,WikiHop,ComplexWebQuestions,DuoRC_Paraphrase,SQuAD2-0,ComQA,DROP,HotpotQA
        - --cuda_device
        - 0,1
        - --sample_size
        - 1
        - --validation_sample_size
        - 1
      env:
        TRAIN_DATASET: $TRAIN_DATASET
      requirements:
        gpuCount: 2