description: >-
  Training BERT-base (MultiQA)
tasks:
  - spec:
      image: MultiQA_with_hyper-param-search-v15
      resultPath: /output
      args:
        - python
        - -u
        - run_experiments.py
        - HotpotQA
        - SQuAD1-1,NewsQA,SearchQA,TriviaQA_wiki,WikiHop,ComplexWebQuestions,DuoRC_Paraphrase,SQuAD2-0,ComQA,HotpotQA
        - --cuda_device
        - 0
        - --sample_size
        - 15000
        - --validation_sample_size
        - 15000
      requirements:
        gpuType: v100
        gpuCount: 1