description: >-
  Training BERT-base wih $TRAIN_DATASET
tasks:
  - spec:
      image: MultiQA_with_hyper-param-search-v10
      resultPath: /output
      args:
        - python
        - -u
        - run_experiments.py
        - $TRAIN_DATASET
        - SQuAD1-1
        - --cuda_device
        - 0
        - --sample_size
        - 1
        - --validation_sample_size
        - 1
      env:
        TRAIN_DATASET: $TRAIN_DATASET
      requirements:
        gpuCount: 1
        gpuType: v100